export * from "./SliderImage"
export * from "./Home"
export * from "./InformationHomePage"
export * from "./Program"
export * from "./BoxExplore"
export * from "./Benefits"
export * from "./TechtrainDifference"
export * from "./Testimonials"