export const routePaths = {
  // auth: {
  //     root: "/auth",
  //     login: "/auth/login",
  //     register: "/auth/register",
  //     forgot: "/auth/forgot",
  //     forgotId: "/auth/forgot-id",
  //     forgotPassword: "/auth/forgot-password",
  //     changePassword: "/auth/change-password",
  //   },
  app: {
    root: "/",
    home: "/home",
    aboutUs: "/about-us",
    steamDiscovery:"/program/steam-discovery",
    techDiscovery:"/program/tech-discovery",
    gdevelopGameDesign:"/program/gdevelop-game-design-world",
    robloxGameDiscovery:"/program/roblox-game-design-world",
    designAdventure:"/program/3d-design-adventure",
    aiGameAdventure:"/program/ai-game-adventure",
  },
  403: "/403",
  500: "/500",
  404: "/404",
}
